language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
  global:
 
before_install:
  
script:
  - curl -XPOST --silent --show-error --user ${TiggerUser}:${TiggerToken} ${TiggerAddress}/job/SDKTesterJenkins/buildWithParameters
  - bash equality_test.sh


branches:
  only:
    - master