language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
  global:
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s"      CONFIGURATION="Debug"    IsIntegrationTestingTask="true"
    - DESTINATION="OS=10.0,name=iPhone 6s"      CONFIGURATION="ReleaseTest"    IsIntegrationTestingTask="false"
before_install:
  
script:
  - travis_wait bash LocalBuild.sh
  
notifications:
  email:
    recipients:
    - panzh@tropo.com
    on_start: always
branches:

